# Generated by Django 5.2.4 on 2025-07-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_studygroup_groupmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
