# Generated by Django 5.2.4 on 2025-07-11 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_chatmessage_groupresource_resourcelike'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sharedlink',
            unique_together=set(),
        ),
    ]
